- hosts: demo

  tasks:
         - name: List combo of two lists
           ansible.builtin.debug:
             msg: "{{ [1,2,3,4,5,6] | zip(['a','b','c','d','e','f']) | list }}"

         - name: Give me shortest combo of two lists
           ansible.builtin.debug:
              msg: "{{ [1,2,3] | zip(['a','b','c','d','e','f']) | list }}"

         - name: Map from List of indices
           ansible.builtin.debug:
             msg: "{{ [0,2] | map('extract', ['x','y','z']) | list }}
                   {{ ['x','y'] | map('extract', {'x': 42, 'y': 31}) | list }}"

         - name: Give me largest permutations (order matters)
           ansible.builtin.debug:
                  msg: "{{ [1,2,3,4,5] | ansible.builtin.permutations | list }}"

         - name: Give me permutations of sets of three
           ansible.builtin.debug:
                msg: "{{ [1,2,3,4,5] | ansible.builtin.permutations(3) | list }}"

         - name: Generate multiple hostnames
           ansible.builtin.debug:
              msg: "{{ ['foo', 'bar'] | product(['com']) | map('join', '.') | join(',') }}"