---
- name: json read demo
  hosts: localhost
  tasks:
    - name: Display Json file content
      shell: cat example.json
      register: result

    - name: retrieve data
      set_fact:
        jsondata: "{{result.stdout | from_json}}"

    - name: setDomainName
      set_fact:
          domain_name: "{{ jsondata | json_query(jmesquery) }}"
      vars:
          jmesquery: 'domain.name'

    - name: setDomainUsername
      set_fact:
          domain_username: "{{ jsondata | json_query(jmesquery) }}"
      vars:
          jmesquery: 'domain.user'

    - name: setDomainPassword
      set_fact:
          domain_password: "{{ jsondata | json_query(jmesquery) }}"
      vars:
          jmesquery: 'domain.password'

    - name: setadmin_Listenport
      set_fact:
          admin_ListenPort: "{{ jsondata | json_query(jmesquery) }}"
      vars:
          jmesquery: 'domain.admin.listenport'

    - name: Debug the values
      debug:
        msg=" Admin Listen Port => {{ admin_ListenPort }}, DomainName => {{ domain_name }}, DomainUserName => {{ domain_username }} , Domain Password => {{ domain_password }}"
