---
- name: URI module demo
  hosts: all
  become: false
  vars:
    server: "https://reqres.in"
    endpoint: "/api/register"
  tasks:
         - name: Create
           ansible.builtin.uri:
             url: "{{ server }}{{ endpoint }}"
             method: POST
             body_format: json
             body: '{
               "email": "eve.holt@reqres.in",
               "password": "pistol"
             }'
             status_code: 200
             timeout: 30
           register: result

         - name: Data
           ansible.builtin.debug:
             var: result.json.id, result.json.token

